baseURL = 'https://www.scottpoulton.com'
languageCode = 'en-us'
title = 'somewhere/nowhere'
theme = "github.com/rhazdon/hugo-theme-hello-friend-ng"

[module]
  [[module.imports]]
    path = "github.com/rhazdon/hugo-theme-hello-friend-ng"

[params]
  customCSS = ["/css/custom.css"]
  homeSubtitle = "welcome to my website"

[params.logo]
  logoMark = "scottpoulton"
  logoText = ">"
  logoCursorDisabled = false
  logoHomeLink = "/"

[[menu.main]]
  name = "home"         
  pageRef = "/"         
  weight = 10           

[[menu.main]]
  name = "about"
  pageRef = "/about"    
  weight = 20

[[menu.main]]
  name = "credits"
  pageRef = "/credits"   
  weight = 30

[[menu.main]]
  name = "links"
  pageRef = "/links"   
  weight = 40